import { formatLocale } from '../i18n';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { BadgeCheck, Clock3, Gavel, WalletCards } from 'lucide-react';
import { useAuthStore } from '../store/auth.store';
import { Card } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { api } from '../lib/api';

const depositLabel: Record<string, string> = { HOLD: 'Caution active', PENDING: 'Validation en cours', CAPTURED: 'Caution débitée', RELEASED: 'Caution libérée' };

export default function DashboardPage() {
  const { user } = useAuthStore(); const [bids, setBids] = useState<any[]>([]); const [deposits, setDeposits] = useState<any[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { Promise.all([api.get('/bids/my'), api.get('/deposits/my')]).then(([myBids, myDeposits]: any) => { setBids(myBids.data || []); setDeposits(myDeposits.data || []); }).finally(() => setLoading(false)); }, []);
  const verified = user?.kycStatus === 'VERIFIED'; const activeDeposit = deposits.find((deposit) => deposit.status === 'HOLD');
  if (loading) return <div className="mx-auto max-w-7xl px-4 py-16 text-center text-slate-500">Préparation de votre espace…</div>;
  return <div className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8">
    <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-bold tracking-[.16em] text-accent">MON ESPACE</p><h1 className="mt-2 text-3xl font-extrabold text-primary">Bonjour, {user?.firstName}.</h1><p className="mt-2 text-sm text-slate-600">Suivez vos vérifications, cautions et enchères depuis un seul endroit.</p></div><Link to="/vehicules"><Button variant="outline">Voir l’inventaire</Button></Link></div>
    {!verified && <section className="mt-8 rounded-2xl border border-[#F2C38E] bg-[#FFF7ED] p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><Clock3 className="mt-0.5 h-5 w-5 shrink-0 text-warning" /><div><h2 className="font-extrabold text-primary">Votre identité est en cours de vérification</h2><p className="mt-1 text-sm leading-6 text-slate-600">Vous pouvez explorer les véhicules, mais la caution et les mises seront disponibles après l’approbation de votre KYC.</p></div></div><span className="self-start rounded-full bg-[#FDE7CC] px-3 py-1 text-xs font-bold text-[#9A4A0A]">EN ATTENTE</span></div></section>}
    <section className="mt-8 grid gap-4 md:grid-cols-3"><Card className="p-5"><p className="text-xs font-bold tracking-wider text-slate-400">IDENTITÉ</p><div className="mt-4 flex items-center gap-3"><span className={`grid h-10 w-10 place-items-center rounded-xl ${verified ? 'bg-green-50 text-success' : 'bg-amber-50 text-warning'}`}><BadgeCheck className="h-5 w-5" /></span><div><p className="font-extrabold text-primary">{verified ? 'Vérifiée' : 'À vérifier'}</p><p className="text-xs text-slate-500">Statut KYC</p></div></div></Card><Card className="p-5"><p className="text-xs font-bold tracking-wider text-slate-400">CAUTION</p><div className="mt-4 flex items-center gap-3"><span className={`grid h-10 w-10 place-items-center rounded-xl ${activeDeposit ? 'bg-green-50 text-success' : 'bg-slate-100 text-slate-500'}`}><WalletCards className="h-5 w-5" /></span><div><p className="font-extrabold text-primary">{activeDeposit ? 'Active' : 'Non active'}</p><p className="text-xs text-slate-500">{activeDeposit ? 'Vous pouvez enchérir' : '600 $ requis'}</p></div></div></Card><Card className="p-5"><p className="text-xs font-bold tracking-wider text-slate-400">MES MISES</p><div className="mt-4 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#FDF0E3] text-accent"><Gavel className="h-5 w-5" /></span><div><p className="font-extrabold text-primary">{bids.length}</p><p className="text-xs text-slate-500">Mise{bids.length > 1 ? 's' : ''} enregistrée{bids.length > 1 ? 's' : ''}</p></div></div></Card></section>
    <section className="mt-8 grid gap-8 lg:grid-cols-[.85fr_1.15fr]"><Card className="p-6"><div className="flex items-center justify-between"><h2 className="text-lg font-extrabold text-primary">Ma caution</h2>{verified && <Link to="/depot" className="text-sm font-bold text-accent">{activeDeposit ? 'Voir le détail' : 'Ajouter'}</Link>}</div>{activeDeposit ? <div className="mt-5 rounded-xl bg-green-50 p-4"><p className="font-bold text-success">600 $ CAD — {depositLabel[activeDeposit.status]}</p><p className="mt-1 text-sm text-slate-600">Préautorisation sécurisée. Elle n’est capturée que si vous remportez un lot.</p></div> : <div className="mt-5 rounded-xl bg-slate-50 p-4"><p className="font-bold text-primary">Aucune caution active</p><p className="mt-1 text-sm text-slate-600">{verified ? 'Réservez votre caution pour activer les enchères.' : 'Votre caution sera disponible une fois votre identité vérifiée.'}</p>{verified && <Link to="/depot"><Button className="mt-4">Réserver ma caution</Button></Link>}</div>}<Link to="/mes-achats"><Button variant="outline" className="mt-5 w-full">Mes achats, documents et transport</Button></Link></Card><Card className="overflow-hidden"><div className="flex items-center justify-between border-b px-6 py-5"><h2 className="text-lg font-extrabold text-primary">Mes dernières mises</h2><span className="text-xs font-semibold text-slate-400">{bids.length} au total</span></div>{bids.length ? <div className="divide-y">{bids.slice(0, 5).map((bid) => <div key={bid.id} className="flex items-center justify-between px-6 py-4"><div><p className="text-sm font-bold text-primary">{bid.auction?.vehicle ? `${bid.auction.vehicle.year} ${bid.auction.vehicle.make} ${bid.auction.vehicle.model}` : 'Enchère automobile'}</p><p className="mt-1 text-xs text-slate-500">{new Date(bid.timestamp).toLocaleDateString(formatLocale())}</p></div><div className="text-right"><p className="font-extrabold text-primary">{bid.actualBidAmount?.toLocaleString(formatLocale())} $</p><p className={`mt-1 text-xs font-bold ${bid.status === 'WINNING' ? 'text-success' : 'text-slate-500'}`}>{bid.status === 'WINNING' ? 'OFFRE GAGNANTE' : 'SURENCHÉRI'}</p></div></div>)}</div> : <div className="px-6 py-12 text-center"><Gavel className="mx-auto h-7 w-7 text-slate-300" /><p className="mt-3 text-sm text-slate-500">Aucune mise pour le moment.</p></div>}</Card></section>
  </div>;
}
