import { Link } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { CheckCircle2, LockKeyhole, ShieldCheck } from 'lucide-react';
import { useAuthStore } from '../store/auth.store';
import { Card } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { StripeDepositForm } from '../components/deposit/StripeDepositForm';
import { api } from '../lib/api';

export default function DepositPage() {
  const { user } = useAuthStore(); const verified = user?.kycStatus === 'VERIFIED'; const [activeDeposit, setActiveDeposit] = useState<any>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { if (!verified) { setLoading(false); return; } api.get('/deposits/my').then((response: any) => setActiveDeposit((response.data || []).find((deposit: any) => deposit.status === 'HOLD') || null)).finally(() => setLoading(false)); }, [verified]);
  return <div className="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl text-center"><p className="text-sm font-bold tracking-[.16em] text-accent">CAUTION DE GARANTIE</p><h1 className="mt-3 text-3xl font-extrabold text-primary">Activez vos enchères en toute sécurité.</h1><p className="mt-3 text-sm leading-6 text-slate-600">La caution est une préautorisation de 600 $ CAD. Elle n’est pas débitée lors de la réservation.</p></div><div className="mt-10 grid gap-7 lg:grid-cols-[1.1fr_.9fr]"><Card className="p-7">{loading ? <p className="text-center text-sm text-slate-600">Vérification de votre caution…</p> : verified && activeDeposit ? <div className="text-center"><ShieldCheck className="mx-auto h-10 w-10 text-success" /><h2 className="mt-4 text-lg font-extrabold text-primary">Votre caution est active</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-600">Vous pouvez participer aux enchères. Aucun paiement supplémentaire n’est requis.</p><Link to="/vehicules"><Button className="mt-6">Voir les véhicules</Button></Link></div> : verified ? <><div className="mb-6 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-amber-50 text-warning"><ShieldCheck className="h-5 w-5" /></span><div><h2 className="font-extrabold text-primary">Activer ma caution</h2><p className="text-sm text-slate-500">Réservation simulée — aucun débit réel</p></div></div><StripeDepositForm onReserved={() => setActiveDeposit({ status: 'HOLD' })} /></> : <div className="text-center"><LockKeyhole className="mx-auto h-9 w-9 text-warning" /><h2 className="mt-4 text-lg font-extrabold text-primary">Vérification d’identité requise</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-600">La caution devient disponible après l’approbation de votre identité par notre équipe.</p><Link to="/tableau-de-bord"><Button className="mt-6">Voir mon statut KYC</Button></Link></div>}</Card><div className="space-y-4"><Card className="p-6"><p className="text-xs font-bold tracking-wider text-slate-400">MONTANT</p><p className="mt-2 text-3xl font-extrabold text-primary">600 $ <span className="text-base">CAD</span></p><p className="mt-2 text-sm text-slate-600">Préautorisation bancaire, non débitée immédiatement.</p></Card><Card className="p-6"><h2 className="font-extrabold text-primary">Ce que cela permet</h2><ul className="mt-4 space-y-3 text-sm text-slate-600"><li className="flex gap-2"><CheckCircle2 className="h-4 w-4 shrink-0 text-success" /> Participer à une ou plusieurs enchères.</li><li className="flex gap-2"><CheckCircle2 className="h-4 w-4 shrink-0 text-success" /> Miser avec votre maximum confidentiel.</li><li className="flex gap-2"><CheckCircle2 className="h-4 w-4 shrink-0 text-success" /> Libération si vous ne remportez aucun lot.</li></ul></Card></div></div></div>;
}
