import { formatLocale } from '../i18n';
import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { CardElement, Elements, useElements, useStripe } from '@stripe/react-stripe-js';
import { loadStripe } from '@stripe/stripe-js';
import toast from 'react-hot-toast';
import { api } from '../lib/api';
import { Card } from '../components/ui/Card';
import { Button } from '../components/ui/Button';

function Checkout({ orderId, isMock, onPaid }: { orderId: string; isMock: boolean; onPaid: () => void }) { const stripe = useStripe(); const elements = useElements(); const [loading, setLoading] = useState(false); const pay = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); try { const response: any = await api.post(`/payments/orders/${orderId}/intent`); if (!response.data.isMock) { const card = elements?.getElement(CardElement); if (!stripe || !card) throw new Error('Carte indisponible.'); const result = await stripe.confirmCardPayment(response.data.clientSecret, { payment_method: { card } }); if (result.error) throw result.error; } await api.post(`/payments/orders/${orderId}/confirm`); toast.success('Paiement confirmé.'); onPaid(); } catch (error: any) { toast.error(error.response?.data?.message || error.message || 'Paiement impossible.'); } finally { setLoading(false); } }; return <form onSubmit={pay} className="space-y-5">{isMock ? <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950">Mode démonstration : aucun montant n’est débité.</div> : <div className="rounded-xl border border-slate-300 bg-white p-4"><p className="mb-3 text-sm font-bold text-slate-700">Carte Stripe de test</p><CardElement options={{ style: { base: { color: '#0B1F33', fontSize: '16px' } } }} /></div>}<Button type="submit" className="w-full" isLoading={loading}>{isMock ? 'Confirmer le paiement simulé' : 'Payer avec Stripe test'}</Button></form>; }

export default function OrderPaymentPage() { const { id } = useParams<{ id: string }>(); const navigate = useNavigate(); const [order, setOrder] = useState<any>(null); const [config, setConfig] = useState<any>(null); useEffect(() => { if (!id) return; Promise.all([api.get('/orders/my'), api.get('/payments/config')]).then(([orders, payment]: any) => { setOrder((orders.data || []).find((item: any) => item.id === id) || null); setConfig(payment.data); }).catch(() => toast.error('Commande introuvable.')); }, [id]); const stripePromise = useMemo(() => config?.publishableKey ? loadStripe(config.publishableKey) : null, [config?.publishableKey]); if (!order || !config) return <div className="p-10 text-center text-slate-600">Chargement du paiement…</div>; if (order.paymentStatus === 'PAID') return <div className="mx-auto max-w-xl p-10 text-center text-slate-700">Cette commande est déjà réglée.</div>; return <div className="mx-auto max-w-xl px-4 py-10"><p className="text-sm font-bold tracking-[.16em] text-accent">PAIEMENT SÉCURISÉ</p><h1 className="mt-2 text-3xl font-extrabold text-primary">Régler votre commande</h1><Card className="mt-7 p-6"><p className="font-extrabold text-primary">{order.orderNumber}</p><p className="mt-1 text-sm text-slate-600">{order.vehicle?.year} {order.vehicle?.make} {order.vehicle?.model}</p><p className="mt-5 text-3xl font-extrabold text-primary">{order.totalAmount?.toLocaleString(formatLocale())} $ CAD</p><div className="mt-6">{config.isMock ? <Elements stripe={null}><Checkout orderId={order.id} isMock onPaid={() => navigate('/mes-paiements')} /></Elements> : stripePromise ? <Elements stripe={stripePromise}><Checkout orderId={order.id} isMock={false} onPaid={() => navigate('/mes-paiements')} /></Elements> : <p className="text-sm text-red-700">Configuration Stripe indisponible.</p>}</div></Card></div>; }
