import { formatLocale } from '../../i18n';
import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { Activity, FileText, ServerCog, Truck } from 'lucide-react';
import { api } from '../../lib/api';
import { Card } from '../../components/ui/Card';
import { Button } from '../../components/ui/Button';
import { useAuthStore } from '../../store/auth.store';

export default function AdminOperationsPage() {
  const [documents, setDocuments] = useState<any[]>([]); const [quotes, setQuotes] = useState<any[]>([]); const [monitoring, setMonitoring] = useState<any>(null); const [sftp, setSftp] = useState<any>(null); const [loading, setLoading] = useState(true); const [syncing, setSyncing] = useState(false);
  const role = useAuthStore((state) => state.user?.role); const canSync = ['ADMIN', 'OPERATIONS'].includes(role || '');
  const load = () => { setLoading(true); Promise.all([api.get('/documents').catch(() => ({ data: [] })), api.get('/transport/quotes').catch(() => ({ data: [] })), api.get('/monitoring/summary').catch(() => ({ data: null })), api.get('/imports/sftp/status').catch(() => ({ data: null }))]).then(([docs, transport, status, config]: any) => { setDocuments(docs.data || []); setQuotes(transport.data || []); setMonitoring(status.data); setSftp(config.data); }).finally(() => setLoading(false)); };
  useEffect(load, []);
  const sync = async () => { setSyncing(true); try { const response: any = await api.post('/imports/sftp/sync'); toast.success(`${response.data.created} véhicule(s) importé(s).`); } catch (error: any) { toast.error(error.response?.data?.message || 'Synchronisation impossible.'); } finally { setSyncing(false); } };
  return <div className="space-y-6"><div><p className="text-sm font-bold tracking-[.16em] text-accent">OPÉRATIONS</p><h2 className="mt-1 text-2xl font-extrabold text-primary">Documents, transport et santé</h2><p className="mt-1 text-sm text-slate-600">Suivez les éléments opérationnels et les connecteurs configurés.</p></div><div className="grid gap-5 md:grid-cols-3"><Card className="p-5"><Activity className="h-5 w-5 text-accent" /><p className="mt-4 text-sm font-bold text-slate-500">État plateforme</p><p className="mt-1 text-2xl font-extrabold text-primary">{monitoring?.status === 'ok' ? 'Opérationnelle' : 'Accès limité'}</p><p className="mt-2 text-xs text-slate-500">{monitoring ? `${monitoring.counters?.liveAuctions || 0} encan(s) actif(s)` : 'Réservé aux rôles autorisés'}</p></Card><Card className="p-5"><ServerCog className="h-5 w-5 text-accent" /><p className="mt-4 text-sm font-bold text-slate-500">Import SFTP</p><p className="mt-1 text-2xl font-extrabold text-primary">{sftp?.configured ? 'Configuré' : 'À configurer'}</p>{canSync && <Button className="mt-3" size="sm" variant="outline" disabled={!sftp?.configured || syncing} onClick={sync}>Synchroniser</Button>}</Card><Card className="p-5"><Truck className="h-5 w-5 text-accent" /><p className="mt-4 text-sm font-bold text-slate-500">Devis transport</p><p className="mt-1 text-2xl font-extrabold text-primary">{loading ? '—' : quotes.length}</p><p className="mt-2 text-xs text-slate-500">Demandes enregistrées</p></Card></div><div className="grid gap-5 lg:grid-cols-2"><Card className="overflow-hidden"><div className="flex items-center gap-2 border-b px-5 py-4"><FileText className="h-5 w-5 text-accent" /><h3 className="font-extrabold text-primary">Documents récents</h3></div><div className="divide-y divide-slate-100">{documents.slice(0, 8).map((document) => <div className="px-5 py-3" key={document.id}><p className="text-sm font-bold text-primary">{document.fileName}</p><p className="mt-1 text-xs text-slate-600">{document.user?.email || 'Client'} · {document.order?.orderNumber || 'Compte'}</p></div>)}{!loading && !documents.length && <p className="p-5 text-sm text-slate-600">Aucun document.</p>}</div></Card><Card className="overflow-hidden"><div className="flex items-center gap-2 border-b px-5 py-4"><Truck className="h-5 w-5 text-accent" /><h3 className="font-extrabold text-primary">Transport récent</h3></div><div className="divide-y divide-slate-100">{quotes.slice(0, 8).map((quote) => <div className="px-5 py-3" key={quote.id}><p className="text-sm font-bold text-primary">{quote.vehicle?.year} {quote.vehicle?.make} {quote.vehicle?.model}</p><p className="mt-1 text-xs text-slate-600">{quote.destinationPostalCode} · {(quote.amount || 0).toLocaleString(formatLocale())} $ · {quote.status}</p></div>)}{!loading && !quotes.length && <p className="p-5 text-sm text-slate-600">Aucun devis.</p>}</div></Card></div></div>;
}
