import { useEffect, useState } from 'react';
import { CarFront, Gavel, Users } from 'lucide-react';
import { Card } from '../../components/ui/Card';
import { api } from '../../lib/api';

const tiles = [{ key: 'users', label: 'Utilisateurs inscrits', icon: Users, tint: 'bg-blue-50 text-blue-700' }, { key: 'vehicles', label: 'Véhicules en inventaire', icon: CarFront, tint: 'bg-amber-50 text-amber-700' }, { key: 'auctions', label: 'Enchères actives', icon: Gavel, tint: 'bg-green-50 text-green-700' }] as const;

export default function AdminDashboardPage() {
  const [stats, setStats] = useState({ users: 0, vehicles: 0, auctions: 0 }); const [loading, setLoading] = useState(true);
  useEffect(() => { Promise.all([api.get('/users').catch(() => ({ data: [] })), api.get('/vehicles').catch(() => ({ data: { total: 0 } })), api.get('/auctions/active').catch(() => ({ data: [] }))]).then(([users, vehicles, auctions]: any) => setStats({ users: Array.isArray(users.data) ? users.data.length : users.data?.length || 0, vehicles: vehicles.data?.total || (Array.isArray(vehicles.data?.data) ? vehicles.data.data.length : 0), auctions: Array.isArray(auctions.data) ? auctions.data.length : auctions.data?.length || 0 })).finally(() => setLoading(false)); }, []);
  return <div><div className="flex items-end justify-between"><div><h2 className="text-2xl font-extrabold text-primary">Vue d’ensemble</h2><p className="mt-1 text-sm text-slate-600">Les indicateurs clés de l’activité AutoBroker QC.</p></div><span className="text-xs font-semibold text-slate-400">Mise à jour à l’ouverture</span></div><div className="mt-8 grid gap-5 md:grid-cols-3">{tiles.map(({ key, label, icon: Icon, tint }) => <Card key={key} className="p-6"><span className={`grid h-11 w-11 place-items-center rounded-xl ${tint}`}><Icon className="h-5 w-5" /></span><p className="mt-6 text-sm font-semibold text-slate-500">{label}</p><p className="mt-1 text-3xl font-extrabold text-primary">{loading ? '—' : stats[key]}</p></Card>)}</div><Card className="mt-7 p-6"><h3 className="font-extrabold text-primary">Priorités opérationnelles</h3><div className="mt-5 grid gap-4 md:grid-cols-3"><div className="rounded-xl bg-[#FFF7ED] p-4 text-sm text-slate-700"><strong className="block text-primary">1. Vérifier les KYC</strong><span className="mt-1 block">Approuver ou rejeter les identités en attente.</span></div><div className="rounded-xl bg-slate-50 p-4 text-sm text-slate-700"><strong className="block text-primary">2. Préparer les lots</strong><span className="mt-1 block">Compléter les informations véhicule et SAAQ.</span></div><div className="rounded-xl bg-green-50 p-4 text-sm text-slate-700"><strong className="block text-primary">3. Superviser les enchères</strong><span className="mt-1 block">Suivre les lots actifs et leurs mises.</span></div></div></Card></div>;
}
